Kleine spellingcorrecties
dnnsoftware/Language-Pack-NL-NL pull request #153
Opened 2021-09-04 19:59 UTC by aspelt

Small corrections

2021-09-05 07:36 UTC, EPTamminga commented
@aspelt Er zijn wat conflicten, die moet je zelf eerst oplossen voordat de PR kan worden verwerkt. Ik heb geen rechten hier om ze te corrigeren.

2021-09-05 07:38 UTC, EPTamminga requested changes
Conflicten eerst oplossen. Misschien ben je van de verkeerde branche gestart of heb je nog niet je eigen repo met de laatste versie bijgewerkt, voordat je ging corrigeren.

2021-09-05 17:29 UTC, aspelt commented
Als het goed is zijn de conflicten nu opgelost. Zak er beter op letten volgende keer!

2021-09-05 17:44 UTC, EPTamminga commented
Geen probleem, ik ben blij dat je kritisch naar de vertaling kijkt.

2021-09-07 17:24 UTC, valadas approved these changes

2021-09-07 17:24 UTC, merged